#!/bin/zsh
if [ "$(playerctl status)" = "Playing" ]; then
  title=`exec playerctl metadata xesam:title`
  artist=`exec playerctl metadata xesam:artist`
  if [ -z "$artist" ]; then
    echo "AD"
  else
    echo "$artist - $title"
  fi
else
  echo "PAUSED"
fi